import type { PrismaClient } from "../generated/prisma/client.js";
import { z } from "zod";
import { AppError } from "../errors/app-error.js";
import { deriveRecentAuthenticationAt,type AccessClaims,type TokenVerifier } from "./jwt.js";
import { requireRecentAuthentication,roles,type Role } from "./permissions.js";
const uuid=z.uuid();
export interface OrganizationAccess{organizationId:string;name:string;slug:string;role:Role;status?:"ACTIVE"|"SUSPENDED"|"ARCHIVED"}
export interface Principal{authUserId:string;userId:string;name:string;email:string;aal:"aal1"|"aal2";authenticatedAt?:number;organization:OrganizationAccess|undefined;organizations:OrganizationAccess[];globalRole?:"SUPER_ADMIN"}
type Row={user_id:string;name:string;email:string;organization_id:string;organization_name:string;organization_slug:string;role:string;organization_status:"ACTIVE"|"SUSPENDED"|"ARCHIVED"};
type PlatformRow={user_id:string;name:string;email:string;active:boolean};
export class AuthService{
 constructor(private prisma:PrismaClient,private verifier:TokenVerifier,private sensitiveAuthMaxAgeSeconds=900){}
 async verifyBearer(header:unknown){if(typeof header!=="string"||!header.startsWith("Bearer "))throw new AppError("UNAUTHORIZED","Credenciais ausentes.",401);const token=header.slice(7).trim();if(!token)throw new AppError("UNAUTHORIZED","Credenciais ausentes.",401);const claims:AccessClaims=await this.verifier.verify(token);return{claims,token};}
 async authenticate(header:unknown,requested:unknown,allowAuto=true):Promise<Principal>{const {claims}=await this.verifyBearer(header);const rows=await this.prisma.$queryRaw<Row[]>`SELECT * FROM private.resolve_auth_context(${claims.sub}::uuid)`;if(rows.length===0)throw new AppError("FORBIDDEN","Usuário sem acesso ativo.",403);const organizations=rows.map(row=>({organizationId:row.organization_id,name:row.organization_name,slug:row.organization_slug,role:z.enum(roles).parse(row.role),status:row.organization_status}));let organization:OrganizationAccess|undefined;if(requested!==undefined){const id=uuid.safeParse(requested);if(!id.success)throw new AppError("VALIDATION_ERROR","Organização inválida.",400);organization=organizations.find(item=>item.organizationId===id.data);if(!organization)throw new AppError("NOT_FOUND","Recurso não encontrado.",404);}else if(allowAuto&&organizations.length===1)organization=organizations[0];const authenticatedAt=deriveRecentAuthenticationAt(claims);return{authUserId:claims.sub,userId:rows[0]!.user_id,name:rows[0]!.name,email:rows[0]!.email,aal:claims.aal,...(authenticatedAt!==undefined?{authenticatedAt}:{}),organization,organizations};}
 async authenticatePlatform(header:unknown):Promise<Principal>{const{claims}=await this.verifyBearer(header);const rows=await this.prisma.$queryRaw<PlatformRow[]>`SELECT * FROM private.resolve_platform_administrator(${claims.sub}::uuid)`;if(!rows[0])throw new AppError("FORBIDDEN","Acesso negado.",403);const authenticatedAt=deriveRecentAuthenticationAt(claims);try{requireRecentAuthentication({aal:claims.aal,...(authenticatedAt!==undefined?{authenticatedAt}:{})},this.sensitiveAuthMaxAgeSeconds)}catch{throw new AppError("MFA_REQUIRED","Autenticação reforçada recente necessária.",403)}return{authUserId:claims.sub,userId:rows[0].user_id,name:rows[0].name,email:rows[0].email,aal:claims.aal,...(authenticatedAt!==undefined?{authenticatedAt}:{}),organization:undefined,organizations:[],globalRole:"SUPER_ADMIN"};}
}
