import type { PrismaClient } from "../generated/prisma/client.js";
import { z } from "zod";
import { AppError } from "../errors/app-error.js";
import type { AccessClaims,TokenVerifier } from "./jwt.js";
import { roles,type Role } from "./permissions.js";
const uuid=z.uuid();
export interface OrganizationAccess{organizationId:string;name:string;slug:string;role:Role}
export interface Principal{authUserId:string;userId:string;name:string;email:string;aal:"aal1"|"aal2";organization:OrganizationAccess|undefined;organizations:OrganizationAccess[]}
type Row={user_id:string;name:string;email:string;organization_id:string;organization_name:string;organization_slug:string;role:string};
export class AuthService{constructor(private prisma:PrismaClient,private verifier:TokenVerifier){} async verifyBearer(header:unknown){if(typeof header!=="string"||!header.startsWith("Bearer "))throw new AppError("UNAUTHORIZED","Credenciais ausentes.",401);const token=header.slice(7).trim();if(!token)throw new AppError("UNAUTHORIZED","Credenciais ausentes.",401);const claims:AccessClaims=await this.verifier.verify(token);return{claims,token};} async authenticate(header:unknown,requested:unknown,allowAuto=true):Promise<Principal>{const {claims}=await this.verifyBearer(header);const rows=await this.prisma.$queryRaw<Row[]>`SELECT * FROM private.resolve_auth_context(${claims.sub}::uuid)`;if(rows.length===0)throw new AppError("FORBIDDEN","Usuário sem acesso ativo.",403);const organizations=rows.map((row)=>({organizationId:row.organization_id,name:row.organization_name,slug:row.organization_slug,role:z.enum(roles).parse(row.role)}));let organization:OrganizationAccess|undefined;if(requested!==undefined){const id=uuid.safeParse(requested);if(!id.success)throw new AppError("VALIDATION_ERROR","Organização inválida.",400);organization=organizations.find((item)=>item.organizationId===id.data);if(!organization)throw new AppError("NOT_FOUND","Recurso não encontrado.",404);}else if(allowAuto&&organizations.length===1)organization=organizations[0];return{authUserId:claims.sub,userId:rows[0]!.user_id,name:rows[0]!.name,email:rows[0]!.email,aal:claims.aal,organization,organizations};}}
