import { createServer } from "node:http";import { exportJWK,generateKeyPair,SignJWT } from "jose";import { afterAll,beforeAll,describe,expect,it } from "vitest";import { createJwtVerifier,deriveRecentAuthenticationAt } from "../src/auth/jwt.js";import { hasPermission,requirePermission,roles } from "../src/auth/permissions.js";
let server:ReturnType<typeof createServer>;let url="";let requests=0;let privateKey:CryptoKey;let jwk:Record<string,unknown>;const issuer="https://issuer.invalid/auth/v1";const subject="11111111-1111-4111-8111-111111111111";
beforeAll(async()=>{const keys=await generateKeyPair("ES256");privateKey=keys.privateKey;jwk={...await exportJWK(keys.publicKey),kid:"key-1",alg:"ES256",use:"sig"};server=createServer((_req,res)=>{requests++;res.setHeader("content-type","application/json");res.end(JSON.stringify({keys:[jwk]}));});await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();if(!address||typeof address==="string")throw new Error("server");url=`http://127.0.0.1:${address.port}/jwks`;});afterAll(()=>new Promise<void>(resolve=>server.close(()=>resolve())));
async function token(overrides:Record<string,unknown>={}){return new SignJWT({role:"authenticated",is_anonymous:false,aal:"aal1",...overrides}).setProtectedHeader({alg:"ES256",kid:"key-1"}).setIssuer(issuer).setAudience("authenticated").setSubject(subject).setIssuedAt().setExpirationTime("5m").sign(privateKey);}
describe("JWT verifier",()=>{it("validates asymmetric claims and caches JWKS",async()=>{requests=0;const verifier=createJwtVerifier({jwksUrl:url,issuer,audience:"authenticated",cooldownDuration:0});await verifier.verify(await token());await verifier.verify(await token());expect(requests).toBe(1);});it("rejects wrong audience",async()=>{const bad=await new SignJWT({role:"authenticated",is_anonymous:false}).setProtectedHeader({alg:"ES256",kid:"key-1"}).setIssuer(issuer).setAudience("other").setSubject(subject).setExpirationTime("5m").sign(privateKey);await expect(createJwtVerifier({jwksUrl:url,issuer,audience:"authenticated"}).verify(bad)).rejects.toMatchObject({statusCode:401});});it("rejects anonymous and expired tokens",async()=>{await expect(createJwtVerifier({jwksUrl:url,issuer,audience:"authenticated"}).verify(await token({is_anonymous:true}))).rejects.toMatchObject({statusCode:401});const expired=await new SignJWT({role:"authenticated",is_anonymous:false}).setProtectedHeader({alg:"ES256",kid:"key-1"}).setIssuer(issuer).setAudience("authenticated").setSubject(subject).setExpirationTime(1).sign(privateKey);await expect(createJwtVerifier({jwksUrl:url,issuer,audience:"authenticated"}).verify(expired)).rejects.toMatchObject({statusCode:401});});});
describe("permission matrix",()=>{it("is deny-by-default per role",()=>{expect(roles.every(role=>hasPermission(role,"clients.read"))).toBe(true);expect(hasPermission("VIEWER","clients.create")).toBe(false);expect(()=>requirePermission("VIEWER","clients.create","aal2")).toThrow();});it.each(["OWNER","ADMIN"] as const)("requires AAL2 for every permitted tenant action by %s",role=>{for(const permission of ["clients.read","clients.create","clients.update","clients.status","organization.manage"] as const){expect(()=>requirePermission(role,permission,"aal1")).toThrowError(expect.objectContaining({statusCode:403,code:"FORBIDDEN"}));expect(()=>requirePermission(role,permission,"aal2")).not.toThrow();}});it.each(["LAWYER","ASSISTANT","FINANCIAL","VIEWER"] as const)("keeps the permission matrix for %s at AAL1",role=>{for(const permission of ["clients.read","clients.create","clients.update","clients.status"] as const){if(hasPermission(role,permission))expect(()=>requirePermission(role,permission,"aal1")).not.toThrow();else expect(()=>requirePermission(role,permission,"aal1")).toThrowError(expect.objectContaining({statusCode:403,code:"FORBIDDEN"}));}});});

describe("recent authentication evidence",()=>{
  it("prefers standard auth_time and never treats token iat as reauthentication",()=>{
    expect(deriveRecentAuthenticationAt({auth_time:1200,amr:[{method:"totp",timestamp:1300}]} as never)).toBe(1200);
    expect(deriveRecentAuthenticationAt({iat:1900} as never)).toBeUndefined();
  });
  it("uses only interactive Supabase AMR methods",()=>{
    expect(deriveRecentAuthenticationAt({amr:[{method:"token_refresh",timestamp:1900},{method:"password",timestamp:1700},{method:"totp",timestamp:1800}]} as never)).toBe(1800);
    expect(deriveRecentAuthenticationAt({amr:[{method:"token_refresh",timestamp:1900}]} as never)).toBeUndefined();
  });
});