import { describe,expect,it,vi } from "vitest";
import { renderEmailTemplate,emailTemplateNames } from "../src/email/templates.js";
import { EmailService,maskEmail,type EmailProvider } from "../src/email/service.js";

describe("Block 4 email foundation",()=>{
 it("renders every transactional template with HTML and plain text",()=>{for(const name of emailTemplateNames){const rendered=renderEmailTemplate(name,{recipientName:"Pessoa",organizationName:"Escritório",actionUrl:"https://example.invalid/action",expiresAt:new Date("2030-01-01T00:00:00Z")});expect(rendered.subject).toContain("JurisVia");expect(rendered.html).toContain("<!doctype html>");expect(rendered.text).toContain("https://example.invalid/action");}});
 it("masks recipients",()=>expect(maskEmail("person@example.com")).toBe("pe***@example.com"));
 it("deduplicates by persisted idempotency key",async()=>{const provider:EmailProvider={send:vi.fn()};const prisma={$queryRaw:vi.fn().mockResolvedValueOnce([{suppressed:false}]).mockResolvedValueOnce([{id:"delivery",provider_message_id:"msg_1",status:"SENT",attempt_count:1,claimed:false}]),emailDelivery:{update:vi.fn()}};const service=new EmailService(prisma as never,provider,{access:"access@example.com",invitations:"invite@example.com",notifications:"notice@example.com"});await expect(service.send({to:"person@example.com",category:"access",template:"securityAlert",data:{},idempotencyKey:"same"})).resolves.toMatchObject({deduplicated:true});expect(provider.send).not.toHaveBeenCalled();});
 it("records provider failure without logging message contents",async()=>{const provider:EmailProvider={send:vi.fn().mockRejectedValue(new Error("provider unavailable"))};const prisma={$queryRaw:vi.fn().mockResolvedValueOnce([{suppressed:false}]).mockResolvedValueOnce([{id:"delivery",provider_message_id:null,status:"SENDING",attempt_count:1,claimed:true}]),emailDelivery:{update:vi.fn().mockResolvedValue({})}};const service=new EmailService(prisma as never,provider,{access:"access@example.com",invitations:"invite@example.com",notifications:"notice@example.com"});await expect(service.send({to:"person@example.com",category:"access",template:"securityAlert",data:{},idempotencyKey:"failure"})).rejects.toThrow("provider unavailable");expect(prisma.emailDelivery.update).toHaveBeenCalledWith({where:{id:"delivery"},data:expect.objectContaining({status:"FAILED",failureCode:"provider_error"})});});
 it("rejects invalid recipients before persistence",async()=>{const prisma={$queryRaw:vi.fn(),emailDelivery:{update:vi.fn()}};const service=new EmailService(prisma as never,{send:vi.fn()},{access:"access@example.com",invitations:"invite@example.com",notifications:"notice@example.com"});await expect(service.send({to:"invalid",category:"access",template:"securityAlert",data:{},idempotencyKey:"invalid"})).rejects.toBeDefined();expect(prisma.$queryRaw).not.toHaveBeenCalled();});
});
