import { spawnSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import dotenv from "dotenv";
import pg from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const env=dotenv.parse(await readFile(resolve(process.cwd(),".env"),"utf8"));
const id={orgA:randomUUID(),orgB:randomUUID(),ownerA:randomUUID(),ownerB:randomUUID(),statusUser:randomUUID(),inactiveUser:randomUUID(),responsibleUser:randomUUID(),noMember:randomUUID(),memA:randomUUID(),memB:randomUUID(),statusMem:randomUUID(),inactiveMem:randomUUID(),responsibleMem:randomUUID(),clientA:randomUUID(),clientA2:randomUUID(),clientB:randomUUID(),caseA:randomUUID(),lawsuit:randomUUID(),task:randomUUID(),document:randomUUID(),publication:randomUUID()};
const marker=randomUUID(); let admin:pg.Client; let runtime:pg.Pool;
async function tenant<T extends pg.QueryResultRow>(org:string,user:string,text:string,values:unknown[]=[]){const c=await runtime.connect();try{await c.query("BEGIN");await c.query("SELECT set_config('app.current_organization_id',$1,true),set_config('app.current_user_id',$2,true)",[org,user]);const result=await c.query<T>(text,values);await c.query("COMMIT");return result;}catch(error){await c.query("ROLLBACK").catch(()=>undefined);throw error;}finally{c.release();}}

beforeAll(async()=>{admin=new pg.Client({connectionString:env.DIRECT_URL,connectionTimeoutMillis:15000});runtime=new pg.Pool({connectionString:env.DATABASE_URL,max:3,connectionTimeoutMillis:15000});await admin.connect();
await admin.query("INSERT INTO users(id,name,email,status,updated_at) VALUES ($1,'A',$2,'ACTIVE',now()),($3,'B',$4,'ACTIVE',now()),($5,'Status',$6,'ACTIVE',now()),($7,'Inactive',$8,'INACTIVE',now()),($9,'None',$10,'ACTIVE',now())",[id.ownerA,`matrix-a-${marker}@example.invalid`,id.ownerB,`matrix-b-${marker}@example.invalid`,id.statusUser,`matrix-status-${marker}@example.invalid`,id.inactiveUser,`matrix-inactive-${marker}@example.invalid`,id.noMember,`matrix-none-${marker}@example.invalid`]);
await admin.query("INSERT INTO users(id,name,email,status,updated_at) VALUES ($1,'Responsible',$2,'ACTIVE',now())",[id.responsibleUser,`matrix-responsible-${marker}@example.invalid`]);
await admin.query("INSERT INTO organizations(id,name,slug,status,updated_at) VALUES ($1,'A',$2,'ACTIVE',now()),($3,'B',$4,'ACTIVE',now())",[id.orgA,`matrix-a-${marker}`,id.orgB,`matrix-b-${marker}`]);
await admin.query("INSERT INTO organization_memberships(id,organization_id,user_id,role,status,updated_at) VALUES ($1,$2,$3,'OWNER','ACTIVE',now()),($4,$5,$6,'OWNER','ACTIVE',now()),($7,$2,$8,'VIEWER','ACTIVE',now()),($9,$2,$10,'VIEWER','ACTIVE',now())",[id.memA,id.orgA,id.ownerA,id.memB,id.orgB,id.ownerB,id.statusMem,id.statusUser,id.inactiveMem,id.inactiveUser]);
await admin.query("INSERT INTO organization_memberships(id,organization_id,user_id,role,status,updated_at) VALUES ($1,$2,$3,'LAWYER','ACTIVE',now())",[id.responsibleMem,id.orgA,id.responsibleUser]);
await admin.query("INSERT INTO clients(id,organization_id,type,name,status,updated_at) VALUES ($1,$2,'INDIVIDUAL','A1','ACTIVE',now()),($3,$2,'INDIVIDUAL','A2','ACTIVE',now()),($4,$5,'INDIVIDUAL','B','ACTIVE',now())",[id.clientA,id.orgA,id.clientA2,id.clientB,id.orgB]);
await admin.query("INSERT INTO cases(id,organization_id,client_id,title,status,responsible_user_id,readiness_score,updated_at) VALUES ($1,$2,$3,'Base','ACTIVE',$4,50,now())",[id.caseA,id.orgA,id.clientA,id.responsibleUser]);
await admin.query("INSERT INTO lawsuits(id,organization_id,case_id,case_number,status,updated_at) VALUES($1,$2,$3,$4,'ACTIVE',now())",[id.lawsuit,id.orgA,id.caseA,`matrix-${marker}`]);
await admin.query("INSERT INTO tasks(id,organization_id,case_id,assigned_to_user_id,title,status,updated_at) VALUES($1,$2,$3,$4,'Matrix task','PENDING',now())",[id.task,id.orgA,id.caseA,id.responsibleUser]);
await admin.query("INSERT INTO client_portal_publications(id,organization_id,case_id,created_by_user_id,type,title,content,published_at,updated_at) VALUES ($1,$2,$3,$4,'STATUS_UPDATE','Base','History',now(),now())",[id.publication,id.orgA,id.caseA,id.ownerA]);
},30000);

afterAll(async()=>{await runtime?.end().catch(()=>undefined);if(!admin)return;try{await admin.query("BEGIN");await admin.query("SELECT set_config('app.allow_admin_cleanup','on',true)");for(const table of ["audit_logs","client_portal_publications","documents","tasks","lawsuits","cases","clients"]){await admin.query(`DELETE FROM ${table} WHERE organization_id=ANY($1::uuid[])`,[[id.orgA,id.orgB]]);}await admin.query("UPDATE organizations SET status='ARCHIVED',archived_at=now() WHERE id=ANY($1::uuid[])",[[id.orgA,id.orgB]]);await admin.query("DELETE FROM organization_memberships WHERE organization_id=ANY($1::uuid[])",[[id.orgA,id.orgB]]);await admin.query("DELETE FROM organizations WHERE id=ANY($1::uuid[])",[[id.orgA,id.orgB]]);await admin.query("DELETE FROM users WHERE id=ANY($1::uuid[])",[[id.ownerA,id.ownerB,id.statusUser,id.inactiveUser,id.responsibleUser,id.noMember]]);await admin.query("COMMIT");}catch(error){await admin.query("ROLLBACK").catch(()=>undefined);throw error;}finally{await admin.end().catch(()=>undefined);}},30000);

describe("RLS and integrity matrix",()=>{
it("rejects organization_id swaps",async()=>{await expect(tenant(id.orgA,id.ownerA,"UPDATE clients SET organization_id=$1 WHERE id=$2",[id.orgB,id.clientA])).rejects.toMatchObject({code:"23514"});});

it("requires an active responsible user when a case becomes active",async()=>{await expect(tenant(id.orgA,id.ownerA,"INSERT INTO cases(id,organization_id,client_id,title,status,responsible_user_id,updated_at) VALUES($1,$2,$3,'Missing','ACTIVE',NULL,now())",[randomUUID(),id.orgA,id.clientA])).rejects.toMatchObject({code:"23514"});const draft=randomUUID();await tenant(id.orgA,id.ownerA,"INSERT INTO cases(id,organization_id,client_id,title,status,responsible_user_id,updated_at) VALUES($1,$2,$3,'Draft','DRAFT',NULL,now())",[draft,id.orgA,id.clientA]);await expect(tenant(id.orgA,id.ownerA,"UPDATE cases SET status='ACTIVE' WHERE id=$1",[draft])).rejects.toMatchObject({code:"23514"});});

it("blocks membership or user changes that invalidate active cases",async()=>{for(const status of ["SUSPENDED","REVOKED"]){await expect(admin.query("UPDATE organization_memberships SET status=$1 WHERE id=$2",[status,id.responsibleMem])).rejects.toMatchObject({code:"23514"});}await expect(admin.query("UPDATE users SET status='INACTIVE' WHERE id=$1",[id.responsibleUser])).rejects.toMatchObject({code:"23514"});});

it("protects an effective owner and permits a transactional handoff",async()=>{await expect(admin.query("UPDATE users SET status='INACTIVE' WHERE id=$1",[id.ownerA])).rejects.toMatchObject({code:"23514"});await admin.query("BEGIN");try{await admin.query("UPDATE organization_memberships SET role='OWNER' WHERE id=$1",[id.statusMem]);await admin.query("UPDATE users SET status='INACTIVE' WHERE id=$1",[id.ownerA]);await admin.query("UPDATE users SET status='ACTIVE' WHERE id=$1",[id.ownerA]);await admin.query("UPDATE organization_memberships SET role='VIEWER' WHERE id=$1",[id.statusMem]);await admin.query("COMMIT");}catch(error){await admin.query("ROLLBACK");throw error;}});
it("denies invited, suspended, revoked and absent memberships",async()=>{try{for(const status of ["INVITED","SUSPENDED","REVOKED"]){await admin.query("UPDATE organization_memberships SET status=$1 WHERE id=$2",[status,id.statusMem]);const result=await tenant<{count:string}>(id.orgA,id.statusUser,"SELECT count(*)::text count FROM clients");expect(result.rows[0]?.count).toBe("0");}const absent=await tenant<{count:string}>(id.orgA,id.noMember,"SELECT count(*)::text count FROM clients");expect(absent.rows[0]?.count).toBe("0");}finally{await admin.query("UPDATE organization_memberships SET status='ACTIVE' WHERE id=$1",[id.statusMem]);}});

it("rejects inactive and cross-tenant responsible users in cases and tasks",async()=>{await expect(tenant(id.orgA,id.ownerA,"INSERT INTO cases(id,organization_id,client_id,title,status,responsible_user_id,updated_at) VALUES($1,$2,$3,'Inactive','ACTIVE',$4,now())",[randomUUID(),id.orgA,id.clientA,id.inactiveUser])).rejects.toMatchObject({code:"23514"});await expect(tenant(id.orgA,id.ownerA,"INSERT INTO cases(id,organization_id,client_id,title,status,responsible_user_id,updated_at) VALUES($1,$2,$3,'Cross','ACTIVE',$4,now())",[randomUUID(),id.orgA,id.clientA,id.ownerB])).rejects.toMatchObject({code:"23514"});await expect(tenant(id.orgA,id.ownerA,"INSERT INTO tasks(id,organization_id,assigned_to_user_id,title,updated_at) VALUES($1,$2,$3,'Inactive',now())",[randomUUID(),id.orgA,id.inactiveUser])).rejects.toMatchObject({code:"23514"});await expect(tenant(id.orgA,id.ownerA,"INSERT INTO tasks(id,organization_id,assigned_to_user_id,title,updated_at) VALUES($1,$2,$3,'Cross',now())",[randomUUID(),id.orgA,id.ownerB])).rejects.toMatchObject({code:"23514"});});

it("accepts readiness boundaries and rejects values outside them",async()=>{for(const score of [null,0,50,100]){await tenant(id.orgA,id.ownerA,"INSERT INTO cases(id,organization_id,client_id,title,status,readiness_score,updated_at) VALUES($1,$2,$3,$4,'DRAFT',$5,now())",[randomUUID(),id.orgA,id.clientA,`Score ${String(score)}`,score]);}for(const score of [-1,101]){await expect(tenant(id.orgA,id.ownerA,"INSERT INTO cases(id,organization_id,client_id,title,status,readiness_score,updated_at) VALUES($1,$2,$3,'Invalid','DRAFT',$4,now())",[randomUUID(),id.orgA,id.clientA,score])).rejects.toMatchObject({code:"23514"});}});

it("enforces document client/case coherence and cross-tenant references",async()=>{await expect(tenant(id.orgA,id.ownerA,"INSERT INTO documents(id,organization_id,case_id,client_id,uploaded_by_user_id,name,storage_path,mime_type,size,status,updated_at) VALUES($1,$2,$3,$4,$5,'Mismatch',$6,'text/plain',1,'UPLOADED',now())",[randomUUID(),id.orgA,id.caseA,id.clientA2,id.ownerA,`matrix/${randomUUID()}`])).rejects.toMatchObject({code:"23514"});await expect(tenant(id.orgA,id.ownerA,"INSERT INTO documents(id,organization_id,case_id,client_id,uploaded_by_user_id,name,storage_path,mime_type,size,status,updated_at) VALUES($1,$2,NULL,$3,$4,'Cross',$5,'text/plain',1,'UPLOADED',now())",[randomUUID(),id.orgA,id.clientB,id.ownerA,`matrix/${randomUUID()}`])).rejects.toMatchObject({code:"23503"});});

it("binds runtime document, publication and audit actors to the current user",async()=>{await tenant(id.orgA,id.ownerA,"INSERT INTO documents(id,organization_id,uploaded_by_user_id,name,storage_path,mime_type,size,status,updated_at) VALUES($1,$2,$3,'Self',$4,'text/plain',1,'UPLOADED',now())",[id.document,id.orgA,id.ownerA,`matrix/self-${marker}`]);await expect(tenant(id.orgA,id.ownerA,"INSERT INTO documents(id,organization_id,uploaded_by_user_id,name,storage_path,mime_type,size,status,updated_at) VALUES($1,$2,$3,'Spoof',$4,'text/plain',1,'UPLOADED',now())",[randomUUID(),id.orgA,id.statusUser,`matrix/spoof-${marker}`])).rejects.toBeDefined();await expect(tenant(id.orgA,id.ownerA,"UPDATE documents SET uploaded_by_user_id=$1 WHERE id=$2",[id.statusUser,id.document])).rejects.toMatchObject({code:"55000"});await tenant(id.orgA,id.ownerA,"INSERT INTO client_portal_publications(id,organization_id,case_id,created_by_user_id,type,title,content,published_at,updated_at) VALUES($1,$2,$3,$4,'MESSAGE','Self','Self',now(),now())",[randomUUID(),id.orgA,id.caseA,id.ownerA]);await expect(tenant(id.orgA,id.ownerA,"INSERT INTO client_portal_publications(id,organization_id,case_id,created_by_user_id,type,title,content,published_at,updated_at) VALUES($1,$2,$3,$4,'MESSAGE','Spoof','Spoof',now(),now())",[randomUUID(),id.orgA,id.caseA,id.statusUser])).rejects.toBeDefined();await tenant(id.orgA,id.ownerA,"INSERT INTO audit_logs(id,organization_id,user_id,action,entity_type) VALUES($1,$2,$3,'self.test','test')",[randomUUID(),id.orgA,id.ownerA]);await expect(tenant(id.orgA,id.ownerA,"INSERT INTO audit_logs(id,organization_id,user_id,action,entity_type) VALUES($1,$2,$3,'spoof.test','test')",[randomUUID(),id.orgA,id.statusUser])).rejects.toBeDefined();await expect(tenant(id.orgA,id.ownerA,"INSERT INTO audit_logs(id,organization_id,user_id,action,entity_type) VALUES($1,$2,NULL,'null.test','test')",[randomUUID(),id.orgA])).rejects.toBeDefined();},15000);

it("denies physical runtime deletes and preserves every row",async()=>{for(const [table,rowId] of [["clients",id.clientA],["cases",id.caseA],["lawsuits",id.lawsuit],["tasks",id.task],["documents",id.document]]){await expect(tenant(id.orgA,id.ownerA,`DELETE FROM ${table} WHERE id=$1`,[rowId])).rejects.toBeDefined();}const preserved=await admin.query<{count:string}>("SELECT ((SELECT count(*) FROM clients WHERE id=$1)+(SELECT count(*) FROM cases WHERE id=$2)+(SELECT count(*) FROM lawsuits WHERE id=$3)+(SELECT count(*) FROM tasks WHERE id=$4)+(SELECT count(*) FROM documents WHERE id=$5))::text count",[id.clientA,id.caseA,id.lawsuit,id.task,id.document]);expect(preserved.rows[0]?.count).toBe("5");});
it("preserves publication history while allowing one-way revocation",async()=>{await expect(tenant(id.orgA,id.ownerA,"UPDATE client_portal_publications SET content='Changed' WHERE id=$1",[id.publication])).rejects.toMatchObject({code:"55000"});const revoked=await tenant(id.orgA,id.ownerA,"UPDATE client_portal_publications SET revoked_at=now() WHERE id=$1 RETURNING id",[id.publication]);expect(revoked.rowCount).toBe(1);await expect(tenant(id.orgA,id.ownerA,"UPDATE client_portal_publications SET revoked_at=NULL WHERE id=$1",[id.publication])).rejects.toMatchObject({code:"55000"});await expect(tenant(id.orgA,id.ownerA,"DELETE FROM client_portal_publications WHERE id=$1",[id.publication])).rejects.toBeDefined();});

it("clears context after error and rollback on a reused connection",async()=>{const c=await runtime.connect();try{await c.query("BEGIN");await c.query("SELECT set_config('app.current_organization_id',$1,true),set_config('app.current_user_id',$2,true)",[id.orgA,id.ownerA]);await expect(c.query("INSERT INTO cases(id,organization_id,client_id,title,status,readiness_score,updated_at) VALUES($1,$2,$3,'Bad','DRAFT',101,now())",[randomUUID(),id.orgA,id.clientA])).rejects.toBeDefined();await c.query("ROLLBACK");let outside=await c.query<{count:string}>("SELECT count(*)::text count FROM clients");expect(outside.rows[0]?.count).toBe("0");for(const [org,user,count] of [[id.orgA,id.ownerA,"2"],[id.orgB,id.ownerB,"1"],[id.orgA,id.ownerA,"2"]]){await c.query("BEGIN");await c.query("SELECT set_config('app.current_organization_id',$1,true),set_config('app.current_user_id',$2,true)",[org,user]);const own=await c.query<{count:string}>("SELECT count(*)::text count FROM clients");expect(own.rows[0]?.count).toBe(count);await c.query("COMMIT");}outside=await c.query<{count:string}>("SELECT count(*)::text count FROM clients");expect(outside.rows[0]?.count).toBe("0");}finally{await c.query("ROLLBACK").catch(()=>undefined);c.release();}});

it("denies runtime writes to organizations and memberships",async()=>{await expect(tenant(id.orgA,id.ownerA,"UPDATE organizations SET name='Forbidden' WHERE id=$1",[id.orgA])).rejects.toBeDefined();await expect(tenant(id.orgA,id.ownerA,"UPDATE organization_memberships SET role='ADMIN' WHERE id=$1",[id.statusMem])).rejects.toBeDefined();await expect(tenant(id.orgA,id.ownerA,"DELETE FROM organization_memberships WHERE id=$1",[id.statusMem])).rejects.toBeDefined();});

it("removes PUBLIC function execution and limits runtime helpers",async()=>{const acl=await admin.query<{name:string;public_execute:boolean;runtime_execute:boolean}>("SELECT p.proname name,has_function_privilege('public',p.oid,'EXECUTE') public_execute,has_function_privilege('jurisvia_app',p.oid,'EXECUTE') runtime_execute FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='private' ORDER BY p.proname");expect(acl.rows.every((row)=>!row.public_execute)).toBe(true);expect(acl.rows.filter((row)=>row.runtime_execute).map((row)=>row.name).sort()).toEqual(['accept_invitation','accept_ownership_transfer','admin_get_organization','admin_get_user','admin_list_organizations','admin_list_users','admin_overview','admin_set_organization_status','archive_current_organization','claim_email_delivery','current_organization_id','current_user_id','has_active_tenant_access','has_tenant_read_access','is_eligible_ownership_target','is_email_suppressed','is_platform_administrator','record_email_webhook','resolve_auth_context','resolve_platform_administrator','rotate_invitation_token','sync_verified_user_email','update_member_role','update_member_status']);});

it("fails provisioning when the effective connection uses the admin role",()=>{const result=spawnSync(process.execPath,["scripts/provision-runtime-role.mjs"],{cwd:process.cwd(),encoding:"utf8",windowsHide:true,env:{...process.env,NODE_ENV:"test",RUNTIME_ROLE_VALIDATION_URL:env.DIRECT_URL}});expect(result.status).not.toBe(0);expect(`${result.stdout}${result.stderr}`).not.toContain(env.DIRECT_URL);expect(`${result.stdout}${result.stderr}`).toContain('runtime_role_validation_failed');});
it("blocks runtime policy, RLS and DDL changes",async()=>{await expect(runtime.query("ALTER POLICY clients_select ON clients USING (true)")).rejects.toBeDefined();await expect(runtime.query("ALTER TABLE clients DISABLE ROW LEVEL SECURITY")).rejects.toBeDefined();await expect(runtime.query("CREATE TABLE runtime_forbidden(id integer)")).rejects.toBeDefined();});
});
