import{beforeEach,describe,expect,it,vi}from"vitest";
import{render,screen,waitFor}from"@testing-library/react";
import userEvent from"@testing-library/user-event";
import{AppContext}from"../components/app/app-context";
import{TeamPage}from"../components/app/team-page";
import{api}from"../lib/api";
import type{Role}from"../lib/auth/types";
vi.mock("../lib/api",()=>({api:vi.fn(),ApiError:class ApiError extends Error{constructor(public status:number,public code:string,message:string){super(message)}}}));
const mockedApi=vi.mocked(api),member={id:"10000000-0000-4000-8000-000000000001",role:"LAWYER" as const,status:"ACTIVE" as const,invitedAt:null,acceptedAt:"2026-09-20T12:00:00Z",createdAt:"2026-09-20T12:00:00Z",updatedAt:"2026-09-20T12:00:00Z",user:{id:"20000000-0000-4000-8000-000000000001",name:"Ana Teste",email:"ana@example.test",status:"ACTIVE"}};
function context(role:Role){const organization={organizationId:"00000000-0000-4000-8000-000000000001",name:"Escritório teste",slug:"teste",role};return{organization,principal:{user:{id:"30000000-0000-4000-8000-000000000001",name:"Gestor Teste",email:"gestor@example.test"},organization,aal:"aal2" as const},refresh:vi.fn()}}
function renderPage(role:Role="OWNER"){return render(<AppContext.Provider value={context(role)}><TeamPage/></AppContext.Provider>)}
function success(members=[member]){mockedApi.mockImplementation(async path=>String(path).includes("invitations")?{data:[],meta:{count:0},requestId:"i"}:{data:members,meta:{count:members.length},requestId:"m"})}
describe("TeamPage",()=>{beforeEach(()=>mockedApi.mockReset());it("exibe loading e estado vazio",async()=>{mockedApi.mockResolvedValue({data:[],meta:{count:0},requestId:"m"});renderPage("LAWYER");expect(screen.getByText("Carregando equipe…")).toBeTruthy();expect(await screen.findByText("Nenhum membro encontrado")).toBeTruthy()});it("oferece erro seguro e nova tentativa",async()=>{mockedApi.mockResolvedValue({get data(){throw new Error("falha simulada")},meta:{},requestId:"error"} as never);renderPage("LAWYER");expect(await screen.findByRole("alert")).toHaveProperty("textContent","Não foi possível carregar a equipe.");expect(screen.getByRole("button",{name:"Tentar novamente"})).toBeTruthy()});it("mantém LAWYER somente leitura e bloqueia demais papéis visualmente",async()=>{success();const{unmount}=renderPage("LAWYER");expect(await screen.findByText("Ana Teste")).toBeTruthy();expect(screen.queryByRole("button",{name:"Convidar pessoa"})).toBeNull();expect(screen.queryByRole("button",{name:"Alterar papel"})).toBeNull();expect(mockedApi.mock.calls.some(([path])=>String(path).includes("invitations"))).toBe(false);unmount();mockedApi.mockReset();renderPage("ASSISTANT");expect(screen.getByText("Acesso indisponível")).toBeTruthy();expect(mockedApi).not.toHaveBeenCalled()});it("OWNER convida sem OWNER ou CLIENT e confirma papel e status",async()=>{success();const user=userEvent.setup();renderPage();expect(await screen.findByText("Ana Teste")).toBeTruthy();await user.click(screen.getByRole("button",{name:"Convidar pessoa"}));const roleSelect=screen.getByRole("dialog").querySelector<HTMLSelectElement>("#invite-role")!;expect(Array.from((roleSelect as HTMLSelectElement).options).map(option=>option.value)).toEqual(["ADMIN","LAWYER","ASSISTANT","FINANCIAL","VIEWER"]);await user.type(screen.getByLabelText("E-mail"),"nova@example.test");await user.click(screen.getByRole("button",{name:"Enviar convite"}));await waitFor(()=>expect(mockedApi).toHaveBeenCalledWith("/api/v1/team/invitations",expect.objectContaining({method:"POST"})));success();await user.click(screen.getByRole("button",{name:"Alterar papel"}));await user.selectOptions(screen.getByLabelText("Novo papel"),"ADMIN");await user.click(screen.getByRole("button",{name:"Confirmar"}));await waitFor(()=>expect(mockedApi).toHaveBeenCalledWith(expect.stringContaining("/role"),expect.objectContaining({body:JSON.stringify({role:"ADMIN"})})));success();await user.click(screen.getByRole("button",{name:"Alterar status"}));await user.click(screen.getByRole("button",{name:"Confirmar"}));await waitFor(()=>expect(mockedApi).toHaveBeenCalledWith(expect.stringContaining("/status"),expect.objectContaining({body:JSON.stringify({status:"SUSPENDED"})})))})});