export const privacySections=[
{id:"apresentacao",title:"Apresentação",body:["Esta página registra uma proposta preliminar de informações de privacidade para o site público e para a futura plataforma JurisVia. Ela ainda depende de revisão jurídica."]},
{id:"escopo",title:"Escopo",body:["O site público atual apresenta o produto. A plataforma autenticada, seus serviços e seus fluxos de dados ainda serão implementados e terão regras próprias antes do uso real."]},
{id:"conceitos",title:"Conceitos básicos",body:["Titular é a pessoa a quem um dado pessoal se refere. Controlador, operador, tratamento e demais papéis deverão ser definidos conforme a operação efetivamente implantada."]},
{id:"site",title:"Dados tratados no site público",body:["O seletor de tema guarda apenas a preferência claro, escuro ou sistema no armazenamento local do navegador. A prévia de contato valida campos localmente e não envia nem armazena os valores preenchidos."]},
{id:"plataforma",title:"Dados que poderão ser tratados na plataforma",body:["A futura plataforma poderá tratar dados de usuários, clientes, casos, processos, tarefas e documentos conforme necessidade, autorização e regras do escritório. Categorias finais dependerão do produto implementado."]},
{id:"finalidades",title:"Finalidades",body:["As finalidades deverão ser específicas e compatíveis com gestão da operação jurídica, controle de acesso, prestação do serviço, suporte e segurança."]},
{id:"bases",title:"Bases legais aplicáveis",body:["As bases legais serão definidas para cada finalidade antes do tratamento real. Esta versão não presume consentimento nem escolhe uma base de forma genérica."]},
{id:"compartilhamento",title:"Compartilhamento",body:["Destinatários, hipóteses e limites de compartilhamento ainda serão definidos. Dados não deverão ser compartilhados sem finalidade, necessidade e fundamento aplicável."]},
{id:"operadores",title:"Operadores e fornecedores",body:["Fornecedores de infraestrutura e operação serão identificados depois da seleção e avaliação contratual. Nenhum fornecedor é declarado nesta versão."]},
{id:"armazenamento",title:"Armazenamento",body:["Locais, ambientes, controles e regiões de armazenamento ainda serão definidos e validados antes da operação."]},
{id:"seguranca",title:"Segurança",body:["A arquitetura deverá adotar isolamento entre escritórios, privilégio mínimo e documentos privados por padrão. Controles só serão apresentados como ativos após implementação e validação."]},
{id:"retencao",title:"Retenção e exclusão",body:["Prazos, critérios de retenção, descarte, exportação e eliminação permanecem a definir por categoria e obrigação aplicável."]},
{id:"direitos",title:"Direitos dos titulares",body:["O canal e o procedimento para solicitações de titulares serão definidos antes do lançamento comercial."]},
{id:"cookies",title:"Cookies e armazenamento local",body:["O site usa armazenamento local apenas para lembrar a preferência de tema. Cookies ou tecnologias adicionais deverão ser documentados antes de serem adotados."]},
{id:"transferencias",title:"Transferências internacionais",body:["Se houver transferência internacional, sua necessidade, destino, garantias e fundamento deverão ser avaliados e informados."]},
{id:"criancas",title:"Crianças e adolescentes",body:["A destinação do serviço e eventuais regras para dados de crianças e adolescentes exigirão avaliação específica antes do tratamento."]},
{id:"alteracoes",title:"Alterações",body:["Esta versão poderá mudar durante a validação do produto. Mudanças materiais deverão ter nova data e comunicação adequada."]},
{id:"contato",title:"Contato",body:["Canal institucional e encarregado: a definir. Não há contato de privacidade operacional nesta versão preliminar."]},
{id:"versao",title:"Data da versão",body:["27/09/2026. Versão preliminar sujeita a revisão jurídica."]}] as const;
export const termsSections=[
{id:"aceitacao",title:"Aceitação",body:["Estes termos são preliminares e descrevem apenas o site público atual. A versão aplicável ao serviço dependerá de revisão jurídica e aceite futuro."]},
{id:"finalidade",title:"Finalidade do site",body:["O site apresenta uma proposta de produto em desenvolvimento e referências demonstrativas. Ele não oferece contratação, pagamento ou acesso à plataforma."]},
{id:"produto",title:"Descrição preliminar do produto",body:["O JurisVia é planejado como software de apoio à gestão jurídica e à comunicação. Recursos, planos, preços e limites ainda poderão mudar."]},
{id:"elegibilidade",title:"Elegibilidade",body:["Critérios de elegibilidade e contratação ainda serão definidos antes do lançamento comercial."]},
{id:"cadastro",title:"Cadastro futuro",body:["Regras de conta, identidade, credenciais, equipe e autorização serão definidas quando a área autenticada for implementada."]},
{id:"responsabilidades",title:"Responsabilidades do usuário",body:["Futuros usuários deverão manter dados corretos, proteger credenciais, respeitar permissões e usar a plataforma conforme a lei e as regras do escritório."]},
{id:"conteudo",title:"Conteúdo jurídico",body:["O software apoiará organização e comunicação. Não prestará serviço jurídico, não substituirá análise profissional e não garantirá resultado."]},
{id:"portal",title:"Portal do cliente",body:["Conteúdo interno não deverá ser publicado automaticamente. O escritório será responsável por escolher e autorizar o que cada cliente poderá visualizar."]},
{id:"pi",title:"Propriedade intelectual",body:["Titularidade, licenças de uso, marcas e conteúdo serão definidos na versão contratual. O nome JurisVia permanece provisório."]},
{id:"disponibilidade",title:"Disponibilidade",body:["Não há serviço operacional, SLA ou garantia de disponibilidade nesta fase pública. Condições futuras dependerão da solução implementada."]},
{id:"terceiros",title:"Serviços de terceiros",body:["Integrações e fornecedores futuros deverão ter termos, responsabilidades e riscos informados quando forem escolhidos."]},
{id:"privacidade",title:"Privacidade",body:["O tratamento de dados deverá observar a política aplicável. A página de privacidade atual também é preliminar."]},
{id:"proibido",title:"Uso proibido",body:["A futura plataforma não deverá ser usada para acesso indevido, violação de direitos, envio de código malicioso ou atividade contrária à lei."]},
{id:"suspensao",title:"Suspensão e encerramento futuros",body:["Hipóteses, garantias, exportação e efeitos de suspensão ou encerramento ainda serão definidos, sem bloquear indevidamente dados essenciais."]},
{id:"limitacoes",title:"Limitações",body:["Limites de responsabilidade, garantias e remédios contratuais dependerão de revisão jurídica e não são definidos por esta página."]},
{id:"alteracoes",title:"Alterações",body:["Os termos poderão mudar antes do lançamento. A versão aplicável deverá indicar data, mudanças e forma de aceite."]},
{id:"legislacao",title:"Legislação e foro",body:["Legislação contratual específica e foro: a definir após identificação da entidade responsável e revisão jurídica."]},
{id:"contato",title:"Contato",body:["Canal institucional: a definir. Esta página não inventa e-mail, endereço ou entidade responsável."]},
{id:"versao",title:"Data da versão",body:["27/09/2026. Versão preliminar sujeita a revisão jurídica."]}] as const;
