import Link from "next/link";
import { ArrowIcon, CheckIcon, ClockIcon, DocumentIcon, LockIcon } from "./icons";

const resources = [
  { title: "Gestão de clientes e casos", phase: "MVP planejado", text: "A proposta reúne clientes e casos judiciais ou extrajudiciais, com responsáveis, partes, fase, status e histórico no contexto do escritório.", points: ["Um cliente poderá ter vários casos", "Cada caso ativo terá responsável interno"] },
  { title: "Processos vinculados aos casos", phase: "MVP planejado", text: "Processos judiciais poderão ser associados ao caso sem transformar o número processual em requisito para trabalhos extrajudiciais.", points: ["Número CNJ opcional e validado quando informado", "Um caso poderá reunir processos relacionados"] },
  { title: "Documentos e coleta guiada", phase: "MVP planejado", text: "Checklists contextuais deverão orientar o envio, a análise e as versões dos documentos sem expor arquivos internos ao cliente por padrão.", points: ["Estados claros da solicitação à aprovação", "Versões preservadas e liberação explícita"] },
  { title: "Tarefas e prazos", phase: "MVP planejado", text: "A rotina deverá conectar atividades, responsáveis, prioridades e prazos ao caso, mantendo origem, fuso e histórico das alterações relevantes.", points: ["Próximos passos atribuídos à equipe", "Prazos críticos com confirmação e alertas"] },
  { title: "Equipe e permissões", phase: "MVP planejado", text: "O acesso será planejado por função e escopo, considerando equipe, unidade, participação no caso e permissões sensíveis específicas.", points: ["Privilégio mínimo desde o convite", "Acesso conforme o contexto do trabalho"] },
  { title: "Painel de Clareza Jurídica", phase: "MVP planejado", text: "A visão interna permanecerá separada do status explicado ao cliente. O escritório decidirá quais atualizações poderão ser publicadas.", points: ["Próximo passo explicado em linguagem acessível", "Conteúdo interno nunca publicado automaticamente"] },
  { title: "Portal do cliente", phase: "MVP planejado", text: "O cliente deverá visualizar somente casos e conteúdos ligados à sua identidade e expressamente liberados pelo escritório.", points: ["Status, pendências e documentos autorizados", "Convite e verificação de identidade"] },
  { title: "Índice de Prontidão do Caso", phase: "MVP planejado", text: "Um indicador operacional interno deverá mostrar se documentação, dados, tarefas críticas e aprovações estão preparados para a próxima etapa.", points: ["Não estima chance de vitória", "Sinaliza preparação operacional"] },
  { title: "Playbooks jurídicos", phase: "Fase 2 planejada", text: "Modelos por área e tipo de caso poderão estruturar fases, checklists, tarefas, responsáveis e mensagens sugeridas para revisão da equipe.", points: ["Conhecimento convertido em processo replicável", "Nenhuma publicação automática ao cliente"] },
  { title: "Auditoria e segurança", phase: "MVP planejado", text: "A arquitetura prevê isolamento entre escritórios, documentos privados por padrão e registro protegido de acessos e ações sensíveis.", points: ["Permissões e publicações auditáveis", "Controles serão validados antes da operação"] },
] as const;

function ResourceVisual({ index }: { index: number }) {
  return <div className="resource-visual" role="img" aria-label="Representação conceitual do recurso"><div className="resource-visual-top"><span>Demonstração conceitual</span><span>Visão planejada</span></div><div className="resource-visual-body"><div className="resource-visual-rail"><i /><i /><i /></div><div className="resource-visual-content"><div className="resource-visual-heading"><span>0{index + 1}</span><b>{index % 2 === 0 ? "Contexto organizado" : "Próximo passo visível"}</b></div><div className="resource-lines"><i /><i /><i /></div><div className="resource-status"><CheckIcon /> Informação com responsável e estado</div></div></div></div>;
}

export function ResourcesPage() {
  return <>
    <section className="resources-hero"><div className="container resources-hero-grid"><div><p className="eyebrow">Recursos planejados</p><h1>Uma base clara para cada parte da rotina jurídica.</h1><p>Esta página apresenta a visão planejada do JurisVia. O produto ainda não está operacional e cada recurso será implementado e validado por etapas.</p><div className="button-row"><Link className="button button-primary button-large" href="#recursos">Explorar os recursos <ArrowIcon /></Link><Link className="button button-secondary button-large" href="/">Voltar à página inicial</Link></div></div><aside className="resources-note"><LockIcon /><div><strong>Planejamento, não disponibilidade.</strong><p>As demonstrações são conceituais, usam conteúdo fictício e não representam funcionalidades já contratáveis.</p></div></aside></div></section>
    <section id="recursos" className="resources-section anchor-target" tabIndex={-1} aria-labelledby="resources-title"><div className="container"><div className="resources-heading"><div><p className="eyebrow">Dez frentes do produto</p><h2 id="resources-title">Do trabalho interno à informação liberada ao cliente.</h2></div><p>Os recursos abaixo seguem o escopo documentado. Playbooks pertencem à Fase 2; os demais integram a visão do MVP, ainda sujeito a implementação e validação.</p></div><ol className="resources-list">{resources.map((resource, index) => <li key={resource.title} className="resource-item"><article><div className="resource-copy"><div className="resource-meta"><span>0{index + 1}</span><span>{resource.phase}</span></div><h3>{resource.title}</h3><p>{resource.text}</p><ul>{resource.points.map((point) => <li key={point}><CheckIcon />{point}</li>)}</ul></div><ResourceVisual index={index} /></article></li>)}</ol></div></section>
    <section className="resources-principle"><div className="container resources-principle-grid"><div><p className="eyebrow">Limites explícitos</p><h2>Controle antes de automação.</h2></div><div className="principle-points"><p><LockIcon /><span><strong>Privado por padrão.</strong> Documentos e conteúdo interno não serão publicados automaticamente.</span></p><p><DocumentIcon /><span><strong>Histórico preservado.</strong> Versões e ações sensíveis deverão manter rastreabilidade.</span></p><p><ClockIcon /><span><strong>Entrega por etapas.</strong> A página descreve intenção de produto, não disponibilidade atual.</span></p></div></div></section>
    <section className="resources-cta"><div className="container resources-cta-inner"><p className="eyebrow">Conheça a proposta</p><h2>Veja como esses recursos se conectam na rotina.</h2><p>A página inicial apresenta a visão do escritório e a comunicação planejada com o cliente.</p><Link className="button button-light button-large" href="/#plataforma">Conhecer a plataforma <ArrowIcon /></Link></div></section>
  </>;
}
