import Link from "next/link";
import { CheckIcon, DocumentIcon, LockIcon } from "./icons";
import { SecurityCarousel } from "./security-carousel";

export function SecurityPage() {
  return <>
    <section className="security-page-hero"><div className="container"><p className="eyebrow">Segurança e privacidade</p><h1>Proteção começa pela forma como o produto é construído.</h1><p>O JurisVia é planejado para separar escritórios, limitar acessos e manter documentos privados. Esses controles ainda dependem de implementação, testes e validação antes do uso com dados reais.</p><p className="security-validation-note"><LockIcon />Princípios e requisitos planejados — não certificações nem controles já operacionais.</p><div className="button-row"><a className="button button-primary button-large" href="#principios">Ver as camadas</a><a className="button button-secondary button-large" href="#separacao">Entender os limites</a></div></div></section>
    <section id="principios" className="principles-section anchor-target" tabIndex={-1}><div className="container"><p className="eyebrow">Princípios do produto</p><h2>Segurança em camadas, com estados transparentes.</h2><p className="security-section-lead">Cada camada abaixo indica se é fundamento, regra, controle planejado ou evolução futura.</p><SecurityCarousel /></div></section>
    <section id="separacao" className="security-detail anchor-target" tabIndex={-1}><div className="container security-detail-grid"><span>01</span><div><h2>A área interna e o portal do cliente têm limites diferentes.</h2><p>Status internos, estratégia, notas e documentos restritos não deverão aparecer no portal. O escritório decidirá quais atualizações e próximos passos poderão ser publicados.</p><small>Separação prevista nas regras de negócio e ainda sujeita a implementação.</small></div></div></section>
    <section id="documentos" className="security-detail section-muted anchor-target" tabIndex={-1}><div className="container security-detail-grid"><span>02</span><div><h2>Privados por padrão, compartilhados com finalidade.</h2><p>Documentos deverão permanecer privados até uma liberação explícita. Versões, estados de análise e critérios de aceite deverão preservar contexto e restringir o acesso a pessoas autorizadas.</p><small>Armazenamento e autorização ainda serão implementados e validados.</small></div></div></section>
    <section id="lgpd" className="security-detail anchor-target" tabIndex={-1}><div className="container security-detail-grid"><span>03</span><div><h2>LGPD é prática contínua, não selo de interface.</h2><p>Adequação exigirá inventário de dados, bases legais, contratos, retenção, atendimento a titulares e revisão profissional. Esta página não afirma conformidade.</p><small>Avaliação jurídica e operacional permanece necessária.</small></div></div></section>
    <section id="evolucao" className="public-state anchor-target" tabIndex={-1}><div className="container"><p className="eyebrow">Evolução transparente</p><h2>O que orienta o produto agora e o que ainda evoluirá.</h2><div className="public-state-grid"><p><CheckIcon /><span><strong>Já orienta o desenho.</strong> Isolamento, privilégio mínimo, publicação controlada e privacidade por padrão são requisitos registrados.</span></p><p><DocumentIcon /><span><strong>Ainda será validado.</strong> Autorização, uploads, auditoria, backups, recuperação e incidentes dependem de implementação e testes.</span></p></div></div></section>
    <section id="responsabilidade-compartilhada" className="security-detail anchor-target" tabIndex={-1}><div className="container security-detail-grid"><span>04</span><div><h2>Proteção também depende de como o escritório usa a plataforma.</h2><p>Convites, permissões, publicação ao cliente e revisão de acessos exigirão decisões responsáveis do escritório. O produto deverá tornar essas escolhas explícitas e rastreáveis.</p><small>Controles técnicos não substituem processos e orientação profissional.</small></div></div></section>
    <section className="resources-cta"><div className="container resources-cta-inner"><p className="eyebrow">Próximos passos</p><h2>Conheça os recursos planejados.</h2><p>Veja como segurança e clareza deverão acompanhar a rotina do produto.</p><div className="button-row"><Link className="button button-light button-large" href="/recursos">Ver recursos</Link><Link className="button button-outline-light button-large" href="/contato">Falar sobre a proposta</Link></div></div></section>
  </>;
}
