"use client";import Link from"next/link";import{useRouter}from"next/navigation";import{useCallback,useEffect,useState}from"react";import{api,ApiError}from"@/lib/api";import{clearOrganizationPreference,readOrganizationPreference,saveOrganizationPreference,selectValidOrganization}from"@/lib/active-organization";import{needsAal2,type Organization,type Principal}from"@/lib/auth/types";import{canAccessTeam}from"@/lib/team";import{createClient}from"@/lib/supabase/client";import{ThemeControl}from"@/components/public/theme-control";import{MfaGate}from"@/components/auth/mfa-gate";import{AppContext}from"./app-context";
type Envelope<T>={data:T;meta:Record<string,unknown>;requestId:string};
export function AppShell({children}:{children:React.ReactNode}){const router=useRouter();const[organizations,setOrganizations]=useState<Organization[]>([]),[organization,setOrganization]=useState<Organization|null>(null),[principal,setPrincipal]=useState<Principal|null>(null),[state,setState]=useState<"loading"|"select"|"ready"|"denied"|"error">("loading"),[message,setMessage]=useState("");
useEffect(()=>{const expired=()=>router.replace("/login?next=/app");window.addEventListener("jurisvia:auth-expired",expired);return()=>window.removeEventListener("jurisvia:auth-expired",expired)},[router]);
const loadPrincipal=useCallback(async(org:Organization)=>{setState("loading");try{const result=await api<Envelope<Principal>>("/api/v1/auth/me",{organizationId:org.organizationId});setPrincipal(result.data);setOrganization(org);saveOrganizationPreference(org.organizationId);setState("ready")}catch(error){if(error instanceof ApiError&&error.status===401){router.replace("/login?next=/app");return}setMessage(error instanceof ApiError?error.message:"Não foi possível validar o acesso.");setState(error instanceof ApiError&&[403,404].includes(error.status)?"denied":"error")}},[router]);
useEffect(()=>{void(async()=>{try{const result=await api<Envelope<Organization[]>>("/api/v1/auth/organizations");setOrganizations(result.data);const selected=selectValidOrganization(result.data,readOrganizationPreference());if(selected)await loadPrincipal(selected);else setState(result.data.length?"select":"denied")}catch(error){if(error instanceof ApiError&&error.status===401){router.replace("/login?next=/app");return}setMessage("Não foi possível carregar seus escritórios.");setState("error")}})()},[loadPrincipal,router]);
async function logout(){clearOrganizationPreference();await createClient().auth.signOut();router.replace("/login");router.refresh()}
if(state==="loading")return <main className="app-state" aria-busy="true"><p>Validando acesso…</p></main>;
if(state==="select")return <main className="app-state"><section><p className="eyebrow">Escritório ativo</p><h1>Escolha onde deseja trabalhar.</h1><p>A preferência fica apenas neste navegador e será validada novamente pela API.</p><div className="organization-list">{organizations.map(org=><button key={org.organizationId} onClick={()=>void loadPrincipal(org)}><strong>{org.name}</strong><span>{org.role}</span></button>)}</div><button className="button button-secondary" onClick={logout}>Sair</button></section></main>;
if(state==="denied"||state==="error"||!organization||!principal)return <main className="app-state"><section><h1>{state==="denied"?"Acesso indisponível":"Não foi possível carregar"}</h1><p>{message||"Sua conta não possui vínculo ativo com um escritório."}</p><button className="button button-secondary" onClick={logout}>Voltar ao login</button></section></main>;
if(needsAal2(organization.role)&&principal.aal!=="aal2")return <main className="app-state"><MfaGate onVerified={()=>void loadPrincipal(organization)}/></main>;
return <AppContext.Provider value={{organization,principal,refresh:()=>loadPrincipal(organization)}}><div className="app-layout"><aside className="app-sidebar"><Link className="app-brand" href="/app">JurisVia</Link><nav aria-label="Área do escritório"><Link href="/app">Visão geral</Link><Link href="/app/clientes">Clientes</Link>{canAccessTeam(organization.role)&&<Link href="/app/equipe">Equipe</Link>}<Link href="/app/configuracoes/perfil">Configurações</Link></nav><div className="app-sidebar-footer"><label htmlFor="organization">Escritório</label><select id="organization" value={organization.organizationId} onChange={e=>{const selected=organizations.find(item=>item.organizationId===e.target.value);if(selected)void loadPrincipal(selected)}}>{organizations.map(org=><option key={org.organizationId} value={org.organizationId}>{org.name}</option>)}</select><span>{organization.role}</span></div></aside><div className="app-main"><header className="app-header"><div><strong>{organization.name}</strong><span>{principal.user.name}</span></div><ThemeControl/><button className="button button-secondary" onClick={logout}>Sair</button></header><main id="conteudo" tabIndex={-1}>{organization.status&&organization.status!=="ACTIVE"&&<div className={`app-lifecycle ${organization.status.toLowerCase()}`} role="status"><strong>{organization.status==="SUSPENDED"?"Organização suspensa":"Organização arquivada"}</strong><span>Os dados permanecem disponíveis para leitura; alterações estão bloqueadas.</span></div>}{children}</main></div></div></AppContext.Provider>}
