import{createHmac,randomBytes}from"node:crypto";import type{PrismaClient}from"../generated/prisma/client.js";import type{Principal}from"../auth/service.js";import{AppError}from"../errors/app-error.js";import{requireRecentAuthentication,requireWritableOrganization}from"../auth/permissions.js";import{withTenant}from"../lib/tenant-context.js";
const ctx=(p:Principal)=>({organizationId:p.organization!.organizationId,userId:p.userId});
export class OrganizationService{constructor(private prisma:PrismaClient,private secret:string,private ttlHours=48,private recentAuthMaxAgeSeconds=900){}
 async get(current:Principal){return withTenant(this.prisma,ctx(current),tx=>tx.organization.findUniqueOrThrow({where:{id:current.organization!.organizationId},select:{id:true,name:true,slug:true,status:true,statusReason:true,suspendedAt:true,archivedAt:true,updatedAt:true,memberships:{where:{role:"OWNER",status:"ACTIVE"},select:{user:{select:{id:true,name:true,email:true}}}}}}));}
 async update(current:Principal,input:{name:string}){requireWritableOrganization(current.organization?.status);if(current.organization?.role!=="OWNER"&&current.organization?.role!=="ADMIN")throw new AppError("FORBIDDEN","Acesso negado.",403);return withTenant(this.prisma,ctx(current),async tx=>{const row=await tx.organization.update({where:{id:current.organization!.organizationId},data:{name:input.name.trim()},select:{id:true,name:true,slug:true,status:true,updatedAt:true}});await tx.auditLog.create({data:{organizationId:row.id,userId:current.userId,action:"organization.updated",entityType:"organization",entityId:row.id}});return row;});}
 async archive(current:Principal,reason:string){requireRecentAuthentication(current,this.recentAuthMaxAgeSeconds);requireWritableOrganization(current.organization?.status);if(current.organization?.role!=="OWNER"||current.aal!=="aal2")throw new AppError("FORBIDDEN","Acesso reforçado necessário.",403);return withTenant(this.prisma,ctx(current),async tx=>{const[row]=await tx.$queryRaw<Array<{id:string;status:"ARCHIVED";archivedAt:Date}>>`SELECT id,status,archived_at AS "archivedAt" FROM private.archive_current_organization(${reason.trim()})`;if(!row)throw new AppError("CONFLICT","Organização indisponível.",409);return row;});}
 async requestTransfer(current:Principal,targetUserId:string){requireRecentAuthentication(current,this.recentAuthMaxAgeSeconds);requireWritableOrganization(current.organization?.status);if(current.organization?.role!=="OWNER"||current.aal!=="aal2")throw new AppError("FORBIDDEN","Acesso reforçado necessário.",403);return withTenant(this.prisma,ctx(current),async tx=>{const[target]=await tx.$queryRaw<Array<{eligible:boolean}>>`SELECT private.is_eligible_ownership_target(${current.organization!.organizationId}::uuid,${targetUserId}::uuid) AS eligible`;if(!target?.eligible)throw new AppError("VALIDATION_ERROR","Destinatário inelegível.",400);await tx.ownershipTransfer.updateMany({where:{organizationId:current.organization!.organizationId,status:"PENDING",expiresAt:{lte:new Date()}},data:{status:"EXPIRED"}});const token=randomBytes(32).toString("base64url"),hash=createHmac("sha256",this.secret).update(token).digest("hex"),expiresAt=new Date(Date.now()+this.ttlHours*3600000);const row=await tx.ownershipTransfer.create({data:{organizationId:current.organization!.organizationId,requestedById:current.userId,targetUserId,tokenHash:hash,expiresAt},select:{id:true,targetUserId:true,status:true,expiresAt:true}});await tx.auditLog.create({data:{organizationId:current.organization!.organizationId,userId:current.userId,action:"ownership_transfer.requested",entityType:"ownership_transfer",entityId:row.id,metadata:{targetUserId}}});return{...row,token};});}
 async acceptTransfer(current:Principal,id:string,token:string){requireRecentAuthentication(current,this.recentAuthMaxAgeSeconds);requireWritableOrganization(current.organization?.status);if(current.aal!=="aal2")throw new AppError("FORBIDDEN","Acesso reforçado necessário.",403);const hash=createHmac("sha256",this.secret).update(token).digest("hex");return withTenant(this.prisma,ctx(current),async tx=>{const [row]=await tx.$queryRaw<Array<{organizationId:string;oldOwnerId:string;newOwnerId:string}>>`SELECT organization_id AS "organizationId",old_owner_id AS "oldOwnerId",new_owner_id AS "newOwnerId" FROM private.accept_ownership_transfer(${id}::uuid,${hash})`;if(!row)throw new AppError("CONFLICT","Transferência indisponível.",409);await tx.auditLog.create({data:{organizationId:row.organizationId,userId:current.userId,action:"ownership_transfer.accepted",entityType:"ownership_transfer",entityId:id,metadata:{oldOwnerId:row.oldOwnerId,newOwnerId:row.newOwnerId}}});return row;});}
 async cancelTransfer(current:Principal,id:string){requireRecentAuthentication(current,this.recentAuthMaxAgeSeconds);requireWritableOrganization(current.organization?.status);if(current.organization?.role!=="OWNER"||current.aal!=="aal2")throw new AppError("FORBIDDEN","Acesso reforçado necessário.",403);return withTenant(this.prisma,ctx(current),async tx=>{const result=await tx.ownershipTransfer.updateMany({where:{id,organizationId:current.organization!.organizationId,requestedById:current.userId,status:"PENDING"},data:{status:"CANCELLED",cancelledAt:new Date()}});if(!result.count)throw new AppError("NOT_FOUND","Recurso não encontrado.",404);return{id,status:"CANCELLED"};});}
}
